import React from 'react';
import ReactDOM from 'react-dom';
import Navbar from  './Navbar.jsx';
import Jumbotron from './Jumbotron.jsx';
import About from './About.jsx';
import Projects from './Projects.jsx';
import Contact from './Contact.jsx';
import ContactForm from './ContactForm.jsx';
import IconLink from './IconLink.jsx';
import Footer from './Footer.jsx';
import Project from './Project.jsx';
import config from '../config/config.js';
import content from './content.js';

ReactDOM.render(<Navbar />, document.getElementById('navbar'));
ReactDOM.render(<Jumbotron />, document.getElementById('jumbotron'));
ReactDOM.render(<About text={content['intro']['text']} image={content['intro']['image']}/>, document.getElementById('about'));
ReactDOM.render(<Projects />, document.getElementById('projects'));
ReactDOM.render(<Project desc={content['project_1']['desc']} image={content['project_1']['image']} title={content['project_1']['title']} link={content['project_1']['link']} github={content['project_1']['github']}/>, document.getElementById("project1"));
ReactDOM.render(<Project desc={content['project_2']['desc']} image={content['project_2']['image']} title={content['project_2']['title']} link={content['project_2']['link']} github={content['project_2']['github']}/>, document.getElementById("project2"));
ReactDOM.render(<Project desc={content['project_3']['desc']} image={content['project_3']['image']} title={content['project_3']['title']} link={content['project_3']['link']} github={content['project_3']['github']} />, document.getElementById("project3"));
// ReactDOM.render(<Project desc={desc} image={projectImage}/>, document.getElementById("project4"));
ReactDOM.render(<Contact />, document.getElementById('contact'));
ReactDOM.render(<ContactForm />, document.getElementById('contact-form'));
ReactDOM.render(<IconLink icon="facebook" link={config.facebookLink} inverseColour={true} />, document.getElementById('fb-icon'));
ReactDOM.render(<IconLink icon="linkedin" link={config.linkedinLink} inverseColour={true} />, document.getElementById('linkedin-icon'));
ReactDOM.render(<IconLink icon="github" link={config.githubLink} inverseColour={true} />, document.getElementById('github-icon'));
ReactDOM.render(<IconLink icon="snapchat-ghost" link={config.snapchatLink} inverseColour={true} />, document.getElementById('snapchat-icon'));
ReactDOM.render(<Footer />, document.getElementById('footer'));

