import React from 'react';
import ReactDOM from 'react-dom';
import Navbar from  './Navbar.jsx';
import Spacing from  './Spacing.jsx';
import Jumbotron from './Jumbotron.jsx';
import About from './About.jsx';
import Projects from './Projects.jsx';
import Contact from './Contact.jsx';
import ContactForm from './ContactForm.jsx';
import IconLink from './IconLink.jsx';
import Footer from './Footer.jsx';
import Project from './Project.jsx';

var desc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquam pharetra lorem, a dignissim ante auctor eu.";
var intro = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vestibulum eros eget cursus suscipit. Donec et tristique lacus, eget rutrum metus. Nam ultrices velit ac dui condimentum aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce nec enim finibus, tempor eros non, hendrerit tortor. In blandit sapien est, vel posuere arcu feugiat sit amet. Maecenas ipsum elit, convallis sed elementum at, dapibus vitae purus. Donec eget ex vitae turpis mollis placerat. Nullam urna purus, laoreet at congue sed, imperdiet sit amet erat. Nunc auctor orci quis eros efficitur ullamcorper.";
var projectImage = "http://via.placeholder.com/480x350";
var profile = "http://via.placeholder.com/480";
ReactDOM.render(<Navbar />, document.getElementById('navbar'));
ReactDOM.render(<Jumbotron />, document.getElementById('jumbotron'));
ReactDOM.render(<About text={intro} image={profile}/>, document.getElementById('about'));
ReactDOM.render(<Projects />, document.getElementById('projects'));
ReactDOM.render(<Project desc={desc} image={projectImage}/>, document.getElementById("project1"));
ReactDOM.render(<Project desc={desc} image={projectImage}/>, document.getElementById("project2"));
ReactDOM.render(<Project desc={desc} image={projectImage}/>, document.getElementById("project3"));
// ReactDOM.render(<Project desc={desc} image={projectImage}/>, document.getElementById("project4"));
ReactDOM.render(<Contact />, document.getElementById('contact'));
ReactDOM.render(<ContactForm />, document.getElementById('contact-form'));
ReactDOM.render(<IconLink icon="facebook" link="https://www.facebook.com/alvin.wong.353" inverseColour={true} />, document.getElementById('fb-icon'));
ReactDOM.render(<IconLink icon="linkedin" link="https://www.linkedin.com/in/alvin-wong-a02814123" inverseColour={true} />, document.getElementById('linkedin-icon'));
ReactDOM.render(<IconLink icon="github" link="https://github.com/alvinwong12" inverseColour={true} />, document.getElementById('github-icon'));
ReactDOM.render(<IconLink icon="snapchat-ghost" link="https://www.snapchat.com/add/alvinwong12" inverseColour={true} />, document.getElementById('snapchat-icon'));
ReactDOM.render(<Footer />, document.getElementById('footer'));

